services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: c-sonarqube
    depends_on:
      - db-sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db-sonarqube:5432/db_sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - '9000:9000'
    networks:
      - sonarqube-net

  db-sonarqube:
    image: postgres:15.2-alpine
    container_name: c-db-sonarqube
    environment:
      POSTGRES_DB: db_sonarqube
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarqube-net

volumes:
  sonarqube_data:
    name: sonarqube_data
  sonarqube_extensions:
    name: sonarqube_extensions
  sonarqube_logs:
    name: sonarqube_logs
  postgresql:
    name: postgresql
  postgresql_data:
    name: postgresql_data

networks:
  sonarqube-net:
    name: sonarqube-net